### ISSUE TITLE
Error: get cluster - Terraform Import

### ISSUE THREAD

**Issue by prabhakarank87** [Mongey/terraform-provider-confluentcloud#64]
@Mongey  When import the existing cluster using terraform import, getting the below error

Command for Import
$terraform import confluentcloud_kafka_cluster.test lkc-x2yvk

Output:-
confluentcloud_kafka_cluster.test: Importing from ID "lkc-x2yvk"...
confluentcloud_kafka_cluster.test: Import prepared!
  Prepared confluentcloud_kafka_cluster for import
confluentcloud_kafka_cluster.test: Refreshing state... [id=lkc-x2yvk]

Error: get cluster: Oops, something went wrong

**Comment by rojopolis** [comment]
I just hit this as well.

**Comment by benweint** [comment]
We hit this as well when trying to `import` an existing cluster. I think this is happening because the cluster resource type is using`ImportStatePassthroughContext` [here](https://github.com/Mongey/terraform-provider-confluentcloud/blob/master/ccloud/resource_kafka_cluster.go#L23), but the `Read` function [here](https://github.com/Mongey/terraform-provider-confluentcloud/blob/4bae9131d4faafe0d8ecf42e6e2d14a7c8a52e10/ccloud/resource_kafka_cluster.go#L246-L250) needs both the cluster ID *and* the environment ID in order to load the cluster.

According to [this doc](https://www.terraform.io/docs/extend/resources/import.html#importer-state-function) from Hashicorp:

> This function requires the Read function to be able to refresh the entire resource with d.Id() ONLY.

So I think in order to support importing existing clusters, this resource type would need to do the thing described here:

> More likely though, if the resource requires multiple attributes and they are not already in the resource ID, Importer State will require a custom function implementation beyond using schema.ImportStatePassthrough, seen below. The ID passed into terraform import should be parsed so d.Set() can be called the required attributes to make the Read function properly operate. The resource ID should also match the ID set during the resource Create function via d.SetId().

**Comment by benweint** [comment]
I opened a PR that should address this here: https://github.com/Mongey/terraform-provider-confluentcloud/pull/74
